In [3]:
import greengraph as gg
import numpy as np
import xarray as xr

In [4]:
from greengraph.importers.databases.inputoutput import useeio
from greengraph.importers.databases.generic import graph_system_from_input_output_matrices

Guseeio = useeio.create_graph()

greengraph | INFO | Found file USEEIOv2.0.1-411.xlsx in local cache.
greengraph | INFO | 13:35:58: Started extracting USEEIO data from Excel file.
greengraph | INFO | 13:36:05: Completed extracting USEEIO data from Excel file. (00:06 min:sec)
greengraph | INFO | 13:36:05: Started modifying USEEIO data.
greengraph | INFO | 13:36:05: Completed modifying USEEIO data. (00:00 min:sec)
greengraph | INFO | 13:36:05: Started creating MultiDiGraph from production matrix.
greengraph | INFO | # of nodes: 411, # of edges: 92,527
greengraph | INFO | 13:36:05: Started creating graph from bi-adjacency matrix.
greengraph | INFO | 13:36:05: Completed creating graph from bi-adjacency matrix. (00:00 min:sec)
greengraph | INFO | 13:36:05: Started adding edges to the graph from adjacency matrix.
greengraph | INFO | 13:36:05: Completed adding edges to the graph from adjacency matrix. (00:00 min:sec)
greengraph | INFO | 13:36:05: Completed creating MultiDiGraph from production matrix. (00:00 min:sec)
greengraph | INFO | 13:36:05: Started creating MultiDiGraph from biosphere matrix.
greengraph | INFO | # of nodes: 2722, # of edges: 204,507
greengraph | INFO | 13:36:05: Started creating graph from bi-adjacency matrix.
greengraph | INFO | 13:36:05: Completed creating graph from bi-adjacency matrix. (00:00 min:sec)
greengraph | INFO | 13:36:05: Started adding edges to the graph from adjacency matrix.
greengraph | INFO | 13:36:06: Completed adding edges to the graph from adjacency matrix. (00:00 min:sec)
greengraph | INFO | 13:36:06: Completed creating MultiDiGraph from biosphere matrix. (00:00 min:sec)
greengraph | INFO | 13:36:06: Started creating MultiDiGraph from indicator matrix.
greengraph | INFO | # of nodes: 23, # of edges: 5,273
greengraph | INFO | 13:36:06: Started creating graph from bi-adjacency matrix.
greengraph | INFO | 13:36:06: Completed creating graph from bi-adjacency matrix. (00:00 min:sec)
greengraph | INFO | 13:36:06: Started adding edges to the graph from adjacency matrix.
greengraph | INFO | 13:36:06: Completed adding edges to the graph from adjacency matrix. (00:00 min:sec)
greengraph | INFO | 13:36:06: Completed creating MultiDiGraph from indicator matrix. (00:00 min:sec)
greengraph | INFO | 13:36:06: Started merging production+extension graphs.
greengraph | INFO | 13:36:07: Completed merging production+extension graphs. (00:00 min:sec)
greengraph | INFO | 13:36:07: Started merging production+extension and indicator graphs.
greengraph | INFO | 13:36:07: Completed merging production+extension and indicator graphs. (00:00 min:sec)
greengraph | INFO | 13:36:07: Started setting node attributes for production+extension+indicator graph.
greengraph | INFO | 13:36:07: Completed setting node attributes for production+extension+indicator graph. (00:00 min:sec)

In [6]:
from greengraph.utility.search import _build_lookup_dictionary

In [4]:
dict_search_attributes = {'name': '1-NAPTHALENAMINE (OR) ALPHA-NAPHTHYLAMINE', 'system': 'useeio'}
tuple(dict_search_attributes.keys())

('name', 'system')

In [9]:
[(node, attr) for node, attr in Guseeio.nodes(data=True) if attr['type'] == 'extension'][42]

('940ab868-1932-4e59-ac52-b9a3b3b9f1b5',
 {'name': '1-NAPTHALENAMINE (OR) ALPHA-NAPHTHYLAMINE',
  'context': 'Waste Flows/Hazardous Waste',
  'unit': 'kg',
  'uuid': '940ab868-1932-4e59-ac52-b9a3b3b9f1b5',
  'index': 42,
  'type': 'extension',
  'system': 'useeio',
  'production': 1.0})

In [21]:
[(n, attr) for n, attr in Guseeio.nodes(data=True) if attr['type'] == 'production'][0:1]

[('99492f69-3793-480d-ae14-8ee38d1d76d2',
  {'name': 'Fresh soybeans, canola, flaxseeds, and other oilseeds',
   'location': 'US',
   'code': '1111A0',
   'category': '11: Agriculture, Forestry, Fishing and Hunting/1111: Oilseed and Grain Farming',
   'unit': 'USD',
   'annual production': 42656016000.0,
   'uuid': '99492f69-3793-480d-ae14-8ee38d1d76d2',
   'index': 0,
   'type': 'production',
   'system': 'useeio',
   'production': 1.0})]

In [10]:
Museeio = Guseeio.generate_matrices(
    matrixformat='dense'
)

greengraph | INFO | 13:38:24: Started Generating production matrix from graph.
greengraph | INFO | 13:38:25: Completed Generating production matrix from graph. (00:01 min:sec)
greengraph | INFO | 13:38:25: Started Generating extension matrix from graph.
greengraph | INFO | 13:38:25: Completed Generating extension matrix from graph. (00:00 min:sec)
greengraph | INFO | 13:38:25: Started Generating indicator matrix from graph.
greengraph | INFO | 13:38:25: Completed Generating indicator matrix from graph. (00:00 min:sec)

In [12]:
Museeio.matrices.keys()

dict_keys(['I-A', 'B', 'Q'])

In [9]:
type(Museeio)

greengraph.core.GreenMatrixContainer

In [15]:
Museeio.lca(demand={Guseeio.get_random_node(type='production', data=False): 10000.0})
Museeio.lcia(format_return='dataframe')

greengraph | INFO | 13:39:26: Started calculating production vector (dense solver).
greengraph | INFO | 13:39:26: Completed calculating production vector (dense solver). (00:00 min:sec)
greengraph | INFO | 13:39:26: Started calculating inventory vector.
greengraph | INFO | 13:39:26: Completed calculating inventory vector. (00:00 min:sec)
greengraph | INFO | 13:39:26: Started calculating impact vector.
greengraph | INFO | 13:39:26: Completed calculating impact vector. (00:00 min:sec)

,name,code,unit,group,description,uuid,index,type,system,amount
0,Renewable Energy Use,RNRG,MJ,Resource Use,Renewable Energy Use,0333b6d4-8da2-40de-ac1a-3e24a46113db,20,indicator,useeio,0.000000e+00
1,Smog Formation Potential,SMOG,kg O3 eq,Impact Potential,Smog Formation,05f3dec6-cbed-416c-b731-fabf46e4bcd3,21,indicator,useeio,2.402698e-01
2,Human Health Toxicity,HTOX,CTUh,Impact Potential,Toxic to Humans,0e55e9c4-248e-44fd-bc29-fa092f18d839,13,indicator,useeio,7.274847e-08
3,Freshwater Ecotoxicity Potential,ETOX,CTUe,Impact Potential,Freshwater Ecotoxicity,1feb4055-9cfc-4641-827a-3738201aaabf,6,indicator,useeio,1.356797e-02
4,Human Health - Respiratory Effects,HRSP,kg PM2.5 eq,Impact Potential,Respiratory Effects,217360d1-a4ff-48ff-a3f2-acabc5aba02d,12,indicator,useeio,1.123882e-03
5,Nonrenewable Energy Use,NNRG,MJ,Resource Use,Nonrenewable Energy Use,33e692b9-cf23-4e2f-af80-8e5352796e45,17,indicator,useeio,0.000000e+00
6,Greenhouse Gases,GHG,kg CO2 eq,Impact Potential,Greenhouse Gases,54975169-c311-461c-8f4a-b5a3756a22ca,8,indicator,useeio,1.648339e+01
7,Value Added,VADD,$,Economic & Social,Value Added,54aa113a-9058-43c2-9205-7333de5bedfb,22,indicator,useeio,6.720009e+03
8,Acidification Potential,ACID,kg SO2 eq,Impact Potential,Acid Rain,5e298fe2-7b69-4654-a414-e43575483218,0,indicator,useeio,8.430931e-03
9,Minerals and Metals Use,MNRL,kg,Resource Use,Minerals and Metals Use,63e2f171-905d-47bf-ae33-ba845d5f00c3,16,indicator,useeio,0.000000e+00
10,Energy Use,ENRG,MJ,Resource Use,Energy Use,6d94077a-ce36-4da2-8ba8-a37452357eab,4,indicator,useeio,0.000000e+00
11,Land use,LAND,m2*yr,Resource Use,Land Use,7005c4f8-5102-4655-89c7-e3d535876783,15,indicator,useeio,7.289111e+00
12,Jobs Supported,JOBS,jobs,Economic & Social,Jobs Supported,75de2ef2-78ce-4ef4-9f81-ac908fe80c5d,14,indicator,useeio,6.604712e-02
13,Commercial Municipal Solid Waste,CMSW,kg,Waste Generated,Municipal Solid Waste,799e472e-ea1e-45cf-abfc-5a9734d10034,2,indicator,useeio,7.869738e+01
14,Human Health - Noncancer,HNCN,CTUh,Impact Potential,Noncancer Disease,8c3dda68-68d4-445e-83e1-8e622f623c7a,11,indicator,useeio,6.847333e-08
15,Commercial RCRA Hazardous Waste,CRHW,kg,Waste Generated,Hazardous Waste,8cf085b6-9cce-4ecf-973f-9d3633fec3d0,3,indicator,useeio,2.497359e-01
16,Ozone Depletion,OZON,kg CFC-11 eq,Impact Potential,Ozone Depletion,9e394dfb-9cbd-458d-8846-f5e67b291021,18,indicator,useeio,0.000000e+00
17,Hazardous Air Pollutants,HAPS,kg,Chemical Releases,Hazardous Air Pollutants,a66c25b2-497c-4bf1-a7b1-94cc4754854d,9,indicator,useeio,2.305232e-03
18,Human Health - Cancer,HCAN,CTUh,Impact Potential,Cancer Disease,c2093783-7ea2-4428-be8b-bb4ef93f42c3,10,indicator,useeio,4.275143e-09
19,Commercial Construction and Demolition Debris,CCDD,kg,Waste Generated,Construction Debris,c85cf501-80da-4dca-a998-408e781393a6,1,indicator,useeio,4.588477e+00
20,Pesticides,PEST,kg,Chemical Releases,Pesticides,cff4b6c8-5d7a-472a-b757-bcd96dc46d3b,19,indicator,useeio,0.000000e+00
21,Freshwater withdrawals,WATR,kg,Resource Use,Water Use,d848911b-b0c2-44b0-a9da-d0d141a3459f,7,indicator,useeio,0.000000e+00
22,Eutrophication Potential,EUTR,kg N eq,Impact Potential,Water Eutrophication,ea2a1dda-8eff-4c36-aafb-8c430280621d,5,indicator,useeio,5.968762e-04

In [16]:
from greengraph.importers.databases.inputoutput import exiobase

In [17]:
Gexio = exiobase.create_graph()

greengraph | INFO | 13:39:42: Started downloading file IOT_2021_ixi.zip from Zenodo.

greengraph | INFO | 13:41:32: Completed downloading file IOT_2021_ixi.zip from Zenodo. (01:50 min:sec)
greengraph | INFO | 13:41:32: Started unpacking Exiobase zip file.
greengraph | INFO | 13:41:34: Completed unpacking Exiobase zip file. (00:01 min:sec)
greengraph | INFO | 13:41:34: Started extracting Exiobase data from txt files.
greengraph | INFO | 13:41:40: Completed extracting Exiobase data from txt files. (00:06 min:sec)
greengraph | INFO | 13:41:41: Started creating MultiDiGraph from production matrix.
greengraph | INFO | # of nodes: 7987, # of edges: 37,918,423
greengraph | INFO | 13:41:41: Started creating graph from bi-adjacency matrix.
greengraph | INFO | 13:41:41: Completed creating graph from bi-adjacency matrix. (00:00 min:sec)
greengraph | INFO | 13:41:41: Started adding edges to the graph from adjacency matrix.
greengraph | INFO | 13:43:01: Completed adding edges to the graph from adjacency matrix. (01:19 min:sec)
greengraph | INFO | 13:43:01: Completed creating MultiDiGraph from production matrix. (01:19 min:sec)
greengraph | INFO | 13:43:01: Started creating MultiDiGraph from biosphere matrix.
greengraph | INFO | # of nodes: 1113, # of edges: 1,236,186
greengraph | INFO | 13:43:01: Started creating graph from bi-adjacency matrix.
greengraph | INFO | 13:43:01: Completed creating graph from bi-adjacency matrix. (00:00 min:sec)
greengraph | INFO | 13:43:01: Started adding edges to the graph from adjacency matrix.
greengraph | INFO | 13:43:07: Completed adding edges to the graph from adjacency matrix. (00:06 min:sec)
greengraph | INFO | 13:43:07: Completed creating MultiDiGraph from biosphere matrix. (00:06 min:sec)
greengraph | INFO | 13:43:07: Started merging production and extension graphs.
greengraph | INFO | 13:44:02: Completed merging production and extension graphs. (00:54 min:sec)
greengraph | INFO | 13:44:02: Started setting node attributes for production and extension graphs.
greengraph | INFO | 13:44:02: Completed setting node attributes for production and extension graphs. (00:00 min:sec)

In [26]:
len(Gexio.edges())

39154609

In [27]:
Mexio = Gexio.generate_matrices(
    matrixformat='dense',
    generate_A = True,
    generate_B = True,
    generate_Q = False,
)

greengraph | INFO | 17:06:31: Started Generating production matrix from graph.
greengraph | INFO | 17:06:54: Completed Generating production matrix from graph. (00:22 min:sec)
greengraph | INFO | 17:06:54: Started Generating extension matrix from graph.
greengraph | INFO | 17:06:55: Completed Generating extension matrix from graph. (00:01 min:sec)

In [24]:
Gexio.get_random_node(type='production', data=True)

('18540369-9067-4d8a-8cb7-a0c3d8db8489',
 {'location': 'WF',
  'name': 'Paper',
  'unit': 'USD',
  'uuid': '18540369-9067-4d8a-8cb7-a0c3d8db8489',
  'index': 7714,
  'type': 'production',
  'system': 'exiobase',
  'production': 1.0})

In [31]:
[
    (n, attr) for n, attr
    in Gexio.nodes(data=True)
    if attr['type']=='production'
    and attr['location'] == 'US'
    and 'chemicals'.lower() in str.lower(attr['name'])
][0:10]

[('59e80178-590b-4d12-a6ea-7a0341796fa8',
  {'location': 'US',
   'name': 'Chemicals nec',
   'unit': 'USD',
   'uuid': '59e80178-590b-4d12-a6ea-7a0341796fa8',
   'index': 4626,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0})]

In [ ]:
[(n, attr) for n, attr in Gexio.nodes(data=True) if attr['type']=='production' and 'copper'.lower() in str.lower(attr['name'])][0:10]

[('051d61d9-82b7-44b1-9dd1-60cba33d0159',
  {'location': 'AT',
   'name': 'Mining of copper ores and concentrates',
   'unit': 'USD',
   'uuid': '051d61d9-82b7-44b1-9dd1-60cba33d0159',
   'index': 25,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('acc1faea-8f4f-4c49-9fef-30c36495c227',
  {'location': 'AT',
   'name': 'Copper production',
   'unit': 'USD',
   'uuid': 'acc1faea-8f4f-4c49-9fef-30c36495c227',
   'index': 79,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('b6233050-62d2-46f0-ab9a-65d7a96b2507',
  {'location': 'AT',
   'name': 'Re-processing of secondary copper into new copper',
   'unit': 'USD',
   'uuid': 'b6233050-62d2-46f0-ab9a-65d7a96b2507',
   'index': 80,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('91dc8d41-75ad-474e-a6f4-f8fbec0eae97',
  {'location': 'BE',
   'name': 'Mining of copper ores and concentrates',
   'unit': 'USD',
   'uuid': '91dc8d41-75ad-474e-a6f4-f8fbec0eae97',
   'index': 188,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('dd0a4925-c9ed-4732-82ab-4ffa8c41d266',
  {'location': 'BE',
   'name': 'Copper production',
   'unit': 'USD',
   'uuid': 'dd0a4925-c9ed-4732-82ab-4ffa8c41d266',
   'index': 242,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('49d7a62e-6dfe-439a-990c-f670d0f24e12',
  {'location': 'BE',
   'name': 'Re-processing of secondary copper into new copper',
   'unit': 'USD',
   'uuid': '49d7a62e-6dfe-439a-990c-f670d0f24e12',
   'index': 243,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('695f04c0-1914-44a0-aeec-14e311340d97',
  {'location': 'BG',
   'name': 'Mining of copper ores and concentrates',
   'unit': 'USD',
   'uuid': '695f04c0-1914-44a0-aeec-14e311340d97',
   'index': 351,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('c8950297-e33a-45ac-a276-3f54fc9cfea3',
  {'location': 'BG',
   'name': 'Copper production',
   'unit': 'USD',
   'uuid': 'c8950297-e33a-45ac-a276-3f54fc9cfea3',
   'index': 405,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('bec79af0-3455-4d1f-8a2d-699d82f7cfc8',
  {'location': 'BG',
   'name': 'Re-processing of secondary copper into new copper',
   'unit': 'USD',
   'uuid': 'bec79af0-3455-4d1f-8a2d-699d82f7cfc8',
   'index': 406,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('3200f0a4-0543-46bd-b370-f86de2292610',
  {'location': 'CY',
   'name': 'Mining of copper ores and concentrates',
   'unit': 'USD',
   'uuid': '3200f0a4-0543-46bd-b370-f86de2292610',
   'index': 514,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0})]

In [36]:
G.get_random_node(type='production', data=True)

('a3f87d91-3a4d-4768-9213-4df1c9bae0e3',
 {'location': 'IE',
  'name': 'Manufacture of electrical machinery and apparatus n.e.c. (31)',
  'unit': 'USD',
  'uuid': 'a3f87d91-3a4d-4768-9213-4df1c9bae0e3',
  'index': 2369,
  'type': 'production',
  'system': 'exiobase',
  'production': 1.0})

In [29]:
Mexio.lca(demand={Gexio.get_random_node(type='production', data=False): 10000.0}, format_return='dataframe')

greengraph | INFO | 17:07:12: Started calculating production vector (dense solver).
greengraph | INFO | 17:07:15: Completed calculating production vector (dense solver). (00:02 min:sec)
greengraph | INFO | 17:07:15: Started calculating inventory vector.
greengraph | INFO | 17:07:15: Completed calculating inventory vector. (00:00 min:sec)

,name,unit,uuid,index,type,system,production,amount
0,Domestic Extraction Used - Metal Ores - Tin ores,kt,0012387a-611d-4371-bf30-210d65ec9f4d,510,extension,exiobase,1.0,0.000000
1,Domestic Extraction Used - Primary Crops - Yams,kt,00bd2694-b6f7-414c-9c19-00af36e87f76,685,extension,exiobase,1.0,0.000000
2,"PM2.5 - non combustion - Pig iron production, ...",kg,00cc12f0-59df-4e7f-be4e-22bdfef16d8b,311,extension,exiobase,1.0,0.000000
3,Cr - combustion - air,kg,00f64749-c6b2-4061-87bc-0b926b058895,43,extension,exiobase,1.0,4.950507
4,Unused Domestic Extraction - Primary Crops - O...,kt,01052b05-424d-479a-a77b-c6e6d758506f,776,extension,exiobase,1.0,0.000000
...,...,...,...,...,...,...,...,...
1108,Water Consumption Blue - Livestock - turkeys,Mm3,ff1b0d13-e057-456a-91fd-1c0062439af0,945,extension,exiobase,1.0,0.000000
1109,Unused Domestic Extraction - Primary Crops - C...,kt,ff23f51d-8e67-45a7-9447-d728bc02789f,832,extension,exiobase,1.0,0.000000
1110,CH4 - non combustion - Mining of coking coal -...,kg,ff3fcb58-3139-4ccc-b919-c135a095d068,71,extension,exiobase,1.0,0.000000
1111,"CO - non combustion - Pig iron production, bla...",kg,ff72ec7a-44ce-4888-ac3f-23989cd7ef75,85,extension,exiobase,1.0,0.000000
1112,Domestic Extraction Used - Primary Crops - Van...,kt,ff90395d-c84b-4df2-a301-87e23e394c75,679,extension,exiobase,1.0,0.000000

In [2]:
from greengraph.importers.databases.ecoinvent import ecoinvent

In [5]:
from pathlib import Path

ecospold_xml_files = ecoinvent._extract_ecospold_xml_files(
    path=Path('/Users/michaelweinold/data/ecoinvent 3.9.1_cutoff_ecoSpold02'),
)

ecoinvent_node_and_edge_data = ecoinvent._prepare_ecoinvent_node_and_edge_lists(
    process_nodes=ecospold_xml_files['process_nodes'],
    product_nodes=ecospold_xml_files['product_nodes'],
    ecosphere_flows_mapping=ecospold_xml_files['ecosphere_flows_mapping'],
    technosphere_edges=ecospold_xml_files['technosphere_edges'],
    ecosphere_edges=ecospold_xml_files['ecosphere_edges'],
)

from greengraph.importers.databases.generic import graph_system_from_node_and_edge_lists

G = graph_system_from_node_and_edge_lists(
    name_system="ecoinvent",
    assign_new_uuids=True,
    str_production_nodes_uuid="brightway_code_process",
    str_extension_nodes_uuid="brightway_code_extension",
    list_dicts_production_nodes_metadata=ecoinvent_node_and_edge_data['nodes_production'],
    list_dicts_extension_nodes_metadata=ecoinvent_node_and_edge_data['nodes_extension'],
    list_tuples_production_edges=ecoinvent_node_and_edge_data['edges_production'],
    list_tuples_extension_edges=ecoinvent_node_and_edge_data['edges_extension'],
)

greengraph | INFO | 09:17:34: Started reading EcoSpold XML files
21238it [02:42, 130.44it/s]
greengraph | INFO | 09:20:17: Completed reading EcoSpold XML files (02:42 min:sec)
greengraph | INFO | 09:20:17: Started adding production nodes to graph.
greengraph | INFO | 09:20:18: Completed adding production nodes to graph. (00:01 min:sec)
greengraph | INFO | 09:20:18: Started adding extension nodes to graph.
greengraph | INFO | 09:20:20: Completed adding extension nodes to graph. (00:01 min:sec)
greengraph | INFO | 09:20:20: Started setting node attributes for production+extension+indicator graph.
greengraph | INFO | 09:20:26: Completed setting node attributes for production+extension+indicator graph. (00:06 min:sec)

In [6]:
[
    (node, attr) for node, attr in G.nodes(data=True)
    if attr['type'] == 'production'
    and attr['name'] == '[sulfonyl]urea-compound production'
]

[('7ba2c5f6-d961-4e8e-a6ec-10e222400760',
  {'type': 'production',
   'name': '[sulfonyl]urea-compound production',
   'product': '[sulfonyl]urea-compound',
   'unit': 'kg',
   'geography': 'Rest-of-World',
   'geography code': 'RoW',
   'classifications': {'By-product classification': 'allocatable product',
    'CPC': '34663: Herbicides, anti-sprouting products and plant-growth regulators'},
   'brightway_code_process': 'a5a1e4525e9e0b3515c688a4daa67b30',
   'brightway_code_product': '69f4ac473f90bb52b5d65ca5221c5252',
   'system': 'ecoinvent',
   'production': 1.0}),
 ('91919ded-43c1-44ee-b62c-dc004e5ef75b',
  {'type': 'production',
   'name': '[sulfonyl]urea-compound production',
   'product': '[sulfonyl]urea-compound',
   'unit': 'kg',
   'geography': 'Europe',
   'geography code': 'RER',
   'classifications': {'By-product classification': 'allocatable product',
    'CPC': '34663: Herbicides, anti-sprouting products and plant-growth regulators'},
   'brightway_code_process': '2e2bf47cd1a70f2d39292b05c9c513a2',
   'brightway_code_product': 'fe648c2c35a7454f98310960312fdea7',
   'system': 'ecoinvent',
   'production': 1.0})]