In [1]:
import greengraph as gg
import numpy as np
import xarray as xr

In [12]:
from greengraph.importers.databases.inputoutput import useeio
from greengraph.importers.databases.generic import graph_system_from_input_output_matrices

Guseeio = useeio.create_graph()

greengraph | INFO | Found file USEEIOv2.0.1-411.xlsx in local cache.
greengraph | INFO | 16:10:32: Started extracting USEEIO data from Excel file.
greengraph | INFO | 16:10:39: Completed extracting USEEIO data from Excel file. (00:06 min:sec)
greengraph | INFO | 16:10:39: Started modifying USEEIO data.
greengraph | INFO | 16:10:39: Completed modifying USEEIO data. (00:00 min:sec)
greengraph | INFO | 16:10:39: Started creating MultiDiGraph from production matrix.
greengraph | INFO | # of nodes: 411, # of edges: 92,527
greengraph | INFO | 16:10:39: Started creating graph from bi-adjacency matrix.
greengraph | INFO | 16:10:39: Completed creating graph from bi-adjacency matrix. (00:00 min:sec)
greengraph | INFO | 16:10:39: Started adding edges to the graph from adjacency matrix.
greengraph | INFO | 16:10:39: Completed adding edges to the graph from adjacency matrix. (00:00 min:sec)
greengraph | INFO | 16:10:39: Completed creating MultiDiGraph from production matrix. (00:00 min:sec)
greengraph | INFO | 16:10:39: Started creating MultiDiGraph from biosphere matrix.
greengraph | INFO | # of nodes: 2722, # of edges: 204,507
greengraph | INFO | 16:10:39: Started creating graph from bi-adjacency matrix.
greengraph | INFO | 16:10:39: Completed creating graph from bi-adjacency matrix. (00:00 min:sec)
greengraph | INFO | 16:10:39: Started adding edges to the graph from adjacency matrix.
greengraph | INFO | 16:10:39: Completed adding edges to the graph from adjacency matrix. (00:00 min:sec)
greengraph | INFO | 16:10:39: Completed creating MultiDiGraph from biosphere matrix. (00:00 min:sec)
greengraph | INFO | 16:10:39: Started creating MultiDiGraph from indicator matrix.
greengraph | INFO | # of nodes: 23, # of edges: 5,273
greengraph | INFO | 16:10:39: Started creating graph from bi-adjacency matrix.
greengraph | INFO | 16:10:39: Completed creating graph from bi-adjacency matrix. (00:00 min:sec)
greengraph | INFO | 16:10:39: Started adding edges to the graph from adjacency matrix.
greengraph | INFO | 16:10:39: Completed adding edges to the graph from adjacency matrix. (00:00 min:sec)
greengraph | INFO | 16:10:39: Completed creating MultiDiGraph from indicator matrix. (00:00 min:sec)
greengraph | INFO | 16:10:39: Started merging production+extension graphs.
greengraph | INFO | 16:10:58: Completed merging production+extension graphs. (00:18 min:sec)
greengraph | INFO | 16:10:58: Started merging production+extension and indicator graphs.
greengraph | INFO | 16:10:59: Completed merging production+extension and indicator graphs. (00:00 min:sec)
greengraph | INFO | 16:10:59: Started setting node attributes for production+extension+indicator graph.
greengraph | INFO | 16:10:59: Completed setting node attributes for production+extension+indicator graph. (00:00 min:sec)

In [13]:
[(node, attr) for node, attr in Guseeio.nodes(data=True) if attr['type'] == 'extension'][0:2]

[('29a639b0-1ea4-4e1f-a3e0-8ac2ef7fef46',
  {'name': '(1S)-Abscisic acid',
   'context': 'emission/air/troposphere/rural/ground-level',
   'unit': 'kg',
   'uuid': '29a639b0-1ea4-4e1f-a3e0-8ac2ef7fef46',
   'index': 0,
   'type': 'extension',
   'system': 'useeio',
   'production': 1.0}),
 ('7455fb66-3c29-4625-9bea-38cde5c0aa5f',
  {'name': '(1S)-Abscisic acid',
   'context': 'emission/ground/human-dominated/agricultural/rural',
   'unit': 'kg',
   'uuid': '7455fb66-3c29-4625-9bea-38cde5c0aa5f',
   'index': 1,
   'type': 'extension',
   'system': 'useeio',
   'production': 1.0})]

In [14]:
[(n, attr) for n, attr in G.nodes(data=True) if attr['type'] == 'production'][0:2]

[('3b7fb9a9-63de-4397-aaf4-8dc26710d6a1',
  {'location': 'AT',
   'name': 'Cultivation of paddy rice',
   'unit': 'USD',
   'uuid': '3b7fb9a9-63de-4397-aaf4-8dc26710d6a1',
   'index': 0,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('7ba0714f-7110-4f5c-9b95-e8a9c4759b49',
  {'location': 'AT',
   'name': 'Cultivation of wheat',
   'unit': 'USD',
   'uuid': '7ba0714f-7110-4f5c-9b95-e8a9c4759b49',
   'index': 1,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0})]

In [15]:
M = Guseeio.generate_matrices(
    matrixformat='dense'
)

greengraph | INFO | 16:12:15: Started Generating production matrix from graph.
greengraph | INFO | 16:12:15: Completed Generating production matrix from graph. (00:00 min:sec)
greengraph | INFO | 16:12:15: Started Generating extension matrix from graph.
greengraph | INFO | 16:12:16: Completed Generating extension matrix from graph. (00:00 min:sec)
greengraph | INFO | 16:12:16: Started Generating indicator matrix from graph.
greengraph | INFO | 16:12:16: Completed Generating indicator matrix from graph. (00:00 min:sec)

In [18]:
M.matrices.keys()

dict_keys(['A', 'B', 'Q'])

In [16]:
type(M)

greengraph.core.GreenMatrixContainer

In [25]:
Guseeio.get_random_node(type='production', data=True)

('de9ce555-8b5f-4f17-8748-6de0e8cfbbaf',
 {'name': 'Sand, gravel, clay, phosphate, other nonmetallic minerals',
  'location': 'US',
  'code': '2123A0',
  'category': '21: Mining, Quarrying, and Oil and Gas Extraction/2123: Nonmetallic Mineral Mining and Quarrying',
  'unit': 'USD',
  'annual production': 17584027000.0,
  'uuid': 'de9ce555-8b5f-4f17-8748-6de0e8cfbbaf',
  'index': 18,
  'type': 'production',
  'system': 'useeio',
  'production': 1.0})

In [31]:
M.lca(demand={Guseeio.get_random_node(type='production', data=False): 10000.0})
M.lcia(format_return='dataframe')

greengraph | INFO | 16:16:49: Started calculating production vector.
greengraph | INFO | 16:16:49: Completed calculating production vector. (00:00 min:sec)
greengraph | INFO | 16:16:49: Started calculating inventory vector.
greengraph | INFO | 16:16:49: Completed calculating inventory vector. (00:00 min:sec)
greengraph | INFO | 16:16:49: Started calculating impact vector.
greengraph | INFO | 16:16:49: Completed calculating impact vector. (00:00 min:sec)

,name,code,unit,group,description,uuid,index,type,system,amount
0,Eutrophication Potential,EUTR,kg N eq,Impact Potential,Water Eutrophication,0dcf25e6-ff29-4bdb-b9f8-744dbb9d4f57,5,indicator,useeio,6.267365e-04
1,Commercial Municipal Solid Waste,CMSW,kg,Waste Generated,Municipal Solid Waste,1045dd68-148e-4993-a347-191e198a2c1b,2,indicator,useeio,3.582996e+01
2,Renewable Energy Use,RNRG,MJ,Resource Use,Renewable Energy Use,24e7d2ed-702e-45af-89cd-2739aa2cba13,20,indicator,useeio,8.411022e+00
3,Jobs Supported,JOBS,jobs,Economic & Social,Jobs Supported,292790e9-3912-4c66-ae25-adbf9a9eb6bc,14,indicator,useeio,1.935980e-02
4,Hazardous Air Pollutants,HAPS,kg,Chemical Releases,Hazardous Air Pollutants,2a5a8751-a654-4558-b11d-9a7ae17f08ae,9,indicator,useeio,2.254190e-04
5,Human Health Toxicity,HTOX,CTUh,Impact Potential,Toxic to Humans,2c4957f9-87bb-4cb7-b13f-be65e8188df5,13,indicator,useeio,3.415072e-09
6,Land use,LAND,m2*yr,Resource Use,Land Use,317c5dad-73bf-46c5-9157-75fdfd7de71e,15,indicator,useeio,2.268952e+00
7,Minerals and Metals Use,MNRL,kg,Resource Use,Minerals and Metals Use,37e86ef2-235b-4f2f-b459-e1c692c45eee,16,indicator,useeio,0.000000e+00
8,Energy Use,ENRG,MJ,Resource Use,Energy Use,556f788b-06e1-46b2-aa3f-e722cd0fed27,4,indicator,useeio,8.411022e+00
9,Ozone Depletion,OZON,kg CFC-11 eq,Impact Potential,Ozone Depletion,5c09eafa-636b-4195-8722-432f2ef43225,18,indicator,useeio,0.000000e+00
10,Greenhouse Gases,GHG,kg CO2 eq,Impact Potential,Greenhouse Gases,6e970d31-da73-4775-9780-199ce9f97de3,8,indicator,useeio,2.192362e+02
11,Nonrenewable Energy Use,NNRG,MJ,Resource Use,Nonrenewable Energy Use,6fc3f153-fa46-4207-a075-a836367071db,17,indicator,useeio,0.000000e+00
12,Human Health - Respiratory Effects,HRSP,kg PM2.5 eq,Impact Potential,Respiratory Effects,7ecf042d-13bf-48a5-871f-48f6ee8be0c4,12,indicator,useeio,4.062691e-04
13,Commercial Construction and Demolition Debris,CCDD,kg,Waste Generated,Construction Debris,82486e60-7bf6-4c43-b90f-157af4aeef02,1,indicator,useeio,7.218308e+00
14,Smog Formation Potential,SMOG,kg O3 eq,Impact Potential,Smog Formation,8398e352-5501-4065-9016-50271d383e93,21,indicator,useeio,2.438450e-01
15,Freshwater withdrawals,WATR,kg,Resource Use,Water Use,85d008aa-6df5-4e91-949f-a6122860bd36,7,indicator,useeio,0.000000e+00
16,Human Health - Noncancer,HNCN,CTUh,Impact Potential,Noncancer Disease,937bb331-3e98-4693-9f12-2be4fff95880,11,indicator,useeio,2.301635e-09
17,Commercial RCRA Hazardous Waste,CRHW,kg,Waste Generated,Hazardous Waste,98cd8ab1-0975-498b-aa36-44be95424c9d,3,indicator,useeio,8.528437e-02
18,Acidification Potential,ACID,kg SO2 eq,Impact Potential,Acid Rain,b54c099c-7e3c-410d-8c62-977bc0342694,0,indicator,useeio,1.051180e-02
19,Human Health - Cancer,HCAN,CTUh,Impact Potential,Cancer Disease,bb20a29e-46ea-448e-8950-78c577a3fcde,10,indicator,useeio,1.113437e-09
20,Pesticides,PEST,kg,Chemical Releases,Pesticides,bc7db949-24b7-4e50-8bdd-f976c904367a,19,indicator,useeio,0.000000e+00
21,Value Added,VADD,$,Economic & Social,Value Added,d9776c8f-4e03-4f12-b1f7-29a5f5a0311f,22,indicator,useeio,7.603376e+03
22,Freshwater Ecotoxicity Potential,ETOX,CTUe,Impact Potential,Freshwater Ecotoxicity,f062a9a8-ecde-445d-9e47-53107c50a332,6,indicator,useeio,1.198027e-03

In [32]:
from greengraph.importers.databases.inputoutput import exiobase

In [33]:
Gexio = exiobase.create_graph()

greengraph | INFO | Found file IOT_2021_ixi.zip in local cache.
greengraph | INFO | 09:54:48: Started unpacking Exiobase zip file.
greengraph | INFO | 09:54:49: Completed unpacking Exiobase zip file. (00:01 min:sec)
greengraph | INFO | 09:54:49: Started extracting Exiobase data from txt files.
greengraph | INFO | 09:54:56: Completed extracting Exiobase data from txt files. (00:06 min:sec)
greengraph | INFO | 09:55:03: Started creating MultiDiGraph from production matrix.
greengraph | INFO | # of nodes: 7987, # of edges: 37,918,423
greengraph | INFO | 09:55:03: Started creating graph from bi-adjacency matrix.
greengraph | INFO | 09:55:03: Completed creating graph from bi-adjacency matrix. (00:00 min:sec)
greengraph | INFO | 09:55:03: Started adding edges to the graph from adjacency matrix.
greengraph | INFO | 09:56:22: Completed adding edges to the graph from adjacency matrix. (01:18 min:sec)
greengraph | INFO | 09:56:22: Completed creating MultiDiGraph from production matrix. (01:18 min:sec)
greengraph | INFO | 09:56:22: Started creating MultiDiGraph from biosphere matrix.
greengraph | INFO | # of nodes: 1113, # of edges: 1,236,186
greengraph | INFO | 09:56:22: Started creating graph from bi-adjacency matrix.
greengraph | INFO | 09:56:22: Completed creating graph from bi-adjacency matrix. (00:00 min:sec)
greengraph | INFO | 09:56:22: Started adding edges to the graph from adjacency matrix.
greengraph | INFO | 09:56:33: Completed adding edges to the graph from adjacency matrix. (00:11 min:sec)
greengraph | INFO | 09:56:33: Completed creating MultiDiGraph from biosphere matrix. (00:11 min:sec)
greengraph | INFO | 09:56:33: Started merging production and extension graphs.
greengraph | INFO | 09:57:37: Completed merging production and extension graphs. (01:04 min:sec)
greengraph | INFO | 09:57:37: Started setting node attributes for production and extension graphs.
greengraph | INFO | 09:57:37: Completed setting node attributes for production and extension graphs. (00:00 min:sec)

In [4]:
Mexio = Gexio.generate_matrices(
    matrixformat='dense',
    generate_A = True,
    generate_B = True,
    generate_Q = False,
)

greengraph | INFO | 08:59:43: Started Generating production matrix from graph.
greengraph | INFO | 09:00:06: Completed Generating production matrix from graph. (00:22 min:sec)
greengraph | INFO | 09:00:06: Started Generating extension matrix from graph.
greengraph | INFO | 09:00:07: Completed Generating extension matrix from graph. (00:00 min:sec)

In [24]:
Gexio.get_random_node(type='production', data=True)

('18540369-9067-4d8a-8cb7-a0c3d8db8489',
 {'location': 'WF',
  'name': 'Paper',
  'unit': 'USD',
  'uuid': '18540369-9067-4d8a-8cb7-a0c3d8db8489',
  'index': 7714,
  'type': 'production',
  'system': 'exiobase',
  'production': 1.0})

In [31]:
[
    (n, attr) for n, attr
    in Gexio.nodes(data=True)
    if attr['type']=='production'
    and attr['location'] == 'US'
    and 'chemicals'.lower() in str.lower(attr['name'])
][0:10]

[('59e80178-590b-4d12-a6ea-7a0341796fa8',
  {'location': 'US',
   'name': 'Chemicals nec',
   'unit': 'USD',
   'uuid': '59e80178-590b-4d12-a6ea-7a0341796fa8',
   'index': 4626,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0})]

In [ ]:
[(n, attr) for n, attr in Gexio.nodes(data=True) if attr['type']=='production' and 'copper'.lower() in str.lower(attr['name'])][0:10]

[('051d61d9-82b7-44b1-9dd1-60cba33d0159',
  {'location': 'AT',
   'name': 'Mining of copper ores and concentrates',
   'unit': 'USD',
   'uuid': '051d61d9-82b7-44b1-9dd1-60cba33d0159',
   'index': 25,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('acc1faea-8f4f-4c49-9fef-30c36495c227',
  {'location': 'AT',
   'name': 'Copper production',
   'unit': 'USD',
   'uuid': 'acc1faea-8f4f-4c49-9fef-30c36495c227',
   'index': 79,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('b6233050-62d2-46f0-ab9a-65d7a96b2507',
  {'location': 'AT',
   'name': 'Re-processing of secondary copper into new copper',
   'unit': 'USD',
   'uuid': 'b6233050-62d2-46f0-ab9a-65d7a96b2507',
   'index': 80,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('91dc8d41-75ad-474e-a6f4-f8fbec0eae97',
  {'location': 'BE',
   'name': 'Mining of copper ores and concentrates',
   'unit': 'USD',
   'uuid': '91dc8d41-75ad-474e-a6f4-f8fbec0eae97',
   'index': 188,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('dd0a4925-c9ed-4732-82ab-4ffa8c41d266',
  {'location': 'BE',
   'name': 'Copper production',
   'unit': 'USD',
   'uuid': 'dd0a4925-c9ed-4732-82ab-4ffa8c41d266',
   'index': 242,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('49d7a62e-6dfe-439a-990c-f670d0f24e12',
  {'location': 'BE',
   'name': 'Re-processing of secondary copper into new copper',
   'unit': 'USD',
   'uuid': '49d7a62e-6dfe-439a-990c-f670d0f24e12',
   'index': 243,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('695f04c0-1914-44a0-aeec-14e311340d97',
  {'location': 'BG',
   'name': 'Mining of copper ores and concentrates',
   'unit': 'USD',
   'uuid': '695f04c0-1914-44a0-aeec-14e311340d97',
   'index': 351,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('c8950297-e33a-45ac-a276-3f54fc9cfea3',
  {'location': 'BG',
   'name': 'Copper production',
   'unit': 'USD',
   'uuid': 'c8950297-e33a-45ac-a276-3f54fc9cfea3',
   'index': 405,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('bec79af0-3455-4d1f-8a2d-699d82f7cfc8',
  {'location': 'BG',
   'name': 'Re-processing of secondary copper into new copper',
   'unit': 'USD',
   'uuid': 'bec79af0-3455-4d1f-8a2d-699d82f7cfc8',
   'index': 406,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0}),
 ('3200f0a4-0543-46bd-b370-f86de2292610',
  {'location': 'CY',
   'name': 'Mining of copper ores and concentrates',
   'unit': 'USD',
   'uuid': '3200f0a4-0543-46bd-b370-f86de2292610',
   'index': 514,
   'type': 'production',
   'system': 'exiobase',
   'production': 1.0})]

In [36]:
G.get_random_node(type='production', data=True)

('a3f87d91-3a4d-4768-9213-4df1c9bae0e3',
 {'location': 'IE',
  'name': 'Manufacture of electrical machinery and apparatus n.e.c. (31)',
  'unit': 'USD',
  'uuid': 'a3f87d91-3a4d-4768-9213-4df1c9bae0e3',
  'index': 2369,
  'type': 'production',
  'system': 'exiobase',
  'production': 1.0})

In [42]:
M.lca(demand={G.get_random_node(type='production', data=False): 10000.0}, format_return='dataframe')

greengraph | INFO | 09:58:47: Started calculating production vector.
greengraph | INFO | 09:58:49: Completed calculating production vector. (00:02 min:sec)
greengraph | INFO | 09:58:49: Started calculating inventory vector.
greengraph | INFO | 09:58:49: Completed calculating inventory vector. (00:00 min:sec)

,name,unit,uuid,index,type,system,production,amount
0,Domestic Extraction Used - Fodder crops - Swed...,kt,0016625b-afc3-4d47-b003-d96bfe15f8a7,489,extension,exiobase,1.0,0.0
1,Domestic Extraction Used - Metal Ores - Gold ores,kt,001aca1b-872f-44c7-8959-aed306fc6d1f,503,extension,exiobase,1.0,0.0
2,Unused Domestic Extraction - Fossil Fuels - Co...,kt,00355b0f-9db6-4b6c-a831-4e4af0f2ae97,880,extension,exiobase,1.0,0.0
3,Water Withdrawal Blue - Electricity - tower - ...,Mm3,0058ffa0-b402-47a9-8416-f174a6f13542,1086,extension,exiobase,1.0,0.0
4,Unused Domestic Extraction - Primary Crops - H...,kt,0074cb7e-a11e-482d-ba7f-40c5b2d8bae0,757,extension,exiobase,1.0,0.0
...,...,...,...,...,...,...,...,...
1108,CO2 - non combustion - Lime production - air,kg,fecfd7ca-fbeb-4675-b008-73bb0e149bb8,93,extension,exiobase,1.0,0.0
1109,CH4 - non combustion - Mining of sub-bituminou...,kg,ff447616-910f-4c33-b988-ed56166fe0e0,73,extension,exiobase,1.0,0.0
1110,Domestic Extraction Used - Primary Crops - Len...,kt,ff7a9e5c-a330-4705-8cd6-93201e5bea9f,601,extension,exiobase,1.0,0.0
1111,Domestic Extraction Used - Metal Ores - Uraniu...,kt,ff9604fd-1939-4979-a351-4597b0241e20,511,extension,exiobase,1.0,0.0
1112,"PM10 - non combustion - Refined lead, unwrough...",kg,ffe702cd-243d-4602-9f2f-dc224a4e613a,271,extension,exiobase,1.0,0.0